Support playing youtube videos as background
likeablob/rpi-wfh-webcam pull request #1
Opened 2020-04-17 08:50 UTC by jtsymon

2020-04-17 08:51 UTC, jtsymon commented
For some reason some videos don't work, I think its an OpenCV problem because Pafy finds the video URL and then it fails to load. Most videos work though, now I just need to make it support changing video without restarting the script and dropping the webcam for a few seconds.

2020-04-17 10:19 UTC, likeablob commented
@jtsymon 
Thank you for the nice PR!  
Yeah, by specifying URL directly we can avoid the extra downloading step.  Let me review this.

2020-04-17 10:28 UTC, likeablob requested changes
Almost LGTM. Could you please check the comment? :pray:

2020-04-17 10:28 UTC, likeablob commented on app.py
> +    parser.add_argument('-u', '--bg-url', metavar='VIDEO_FILE',
Could you also change `metavar` to 'YOUTUBE_URL' or something like that?
```suggestion
    parser.add_argument('-u', '--bg-url', metavar='YOUTUBE_URL,
```

2020-04-18 11:50 UTC, likeablob commented
@jtsymon Thanks :+1: ! I'd like to merge this PR.

BTW, Are you being forced to use a "secured" laptop too?

2020-04-18 11:50 UTC, merged

2020-04-19 00:23 UTC, jtsymon commented
No, I'm just running Linux and liked this better than https://github.com/fangfufu/Linux-Fake-Background-Webcam which uses NodeJS as well as Python :slightly_smiling_face:

2020-04-20 02:56 UTC, likeablob commented
@jtsymon Aha, that's nice to hear haha.

> now I just need to make it support changing video without restarting the script and dropping the webcam for a few seconds.

Regarding this matter, I'm not 100% sure but,  [`akvcam`](https://github.com/webcamoid/akvcam) could be used as an alternative to `v4l2loopback`, Since the former has the default picture feature.

> Configurable default picture in case no input signal available.